### ISSUE TITLE
internet gelöscht

### ISSUE THREAD

**Issue by doim5** [lagmoellertim/3dprinter-timer-react#1]
deine app hat mein internet gelöscht, hilfe, mach das wieder richtig

**Comment by lagmoellertim** [comment]
Ja das tut mir sehr leid, dass ist einer die Fehler die bei der Benutzung auftreten können.
Sind sie ein Mensch oder ein Roboter?

**Comment by doim5** [comment]
roboter natürlich

**Comment by lagmoellertim** [comment]
01100100 01110101 00100000 01101000 01100001 01110011 01110100 00100000 01110111 01101001 01110010 01101011 01101100 01101001 01100011 01101000 00100000 01100101 01101001 01101110 01100101 01101110 00100000 01100010 01101001 01101110 11000011 10100100 01110010 11000011 10111100 01100010 01100101 01110010 01110011 01100101 01110100 01111010 01100101 01110010 00100000 01100111 01100101 01101110 01110101 01110100 01111010 01110100 00100000 01100100 01110101 00100000 01101101 01100101 01101110 01110011 01100011 01101000 00111111

**Comment by doim5** [comment]
01101110 01100101 01101001 01101110 00100000 01101110 01100001 01110100 11111100 01110010 01101100 01101001 01100011 01101000 00100000 01101110 01101001 01100011 01101000 01110100

**Comment by lagmoellertim** [comment]
01000111 01110101 01110100 01100101 01110010 00100000 01010010 01101111 01100010 01101111 01110100 01100101 01110010 00101100 00100000 01100100 01100001 01100110 11000011 10111100 01110010 00100000 01100010 01100101 01101011 01101111 01101101 01101101 01110011 01110100 00100000 01100100 01110101 00100000 01100101 01101001 01101110 00100000 01001100 01100101 01100011 01101011 01100101 01110010 01101100 01101001 00100001

**Comment by SgtGEoRge23** [comment]
This should help:
https://giphy.com/gifs/cat-weird-bra-p4xp4BjHIdane

**Comment by doim5** [comment]
01101110 01110101 01101100 01101100 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01101110 01110101 01101100 01101100 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01101110 01110101 01101100 01101100 00100000 01101110 01110101 01101100 01101100 00101110 00100000 01101110 01110101 01101100 01101100 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01101110 01110101 01101100 01101100 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00101110 00100000 01101110 01110101 01101100 01101100 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01101110 01110101 01101100 01101100 00100000 01100101 01101001 01101110 01110011 00100000 01100101 01101001 01101110 01110011 00100000 01101110 01110101 01101100 01101100 00100000 01101110 01110101 01101100 01101100

**Comment by lagmoellertim** [comment]
> This should help:
> https://giphy.com/gifs/cat-weird-bra-p4xp4BjHIdane

Ich denke der Nutzer hat es schon beantwortet, eine sehr gute Antwort! Vielen Dank für ihre Hilfe allerseits!
